import { HttpException, HttpStatus } from '@nestjs/common';

export const CATALOG_ERROR_CODES = {
  FORBIDDEN: 'CATALOG_FORBIDDEN',
  COSTS_FORBIDDEN: 'CATALOG_COSTS_FORBIDDEN',
  CATEGORY_NOT_FOUND: 'CATALOG_CATEGORY_NOT_FOUND',
  CATEGORY_NAME_ALREADY_EXISTS: 'CATALOG_CATEGORY_NAME_ALREADY_EXISTS',
  CATEGORY_SLUG_ALREADY_EXISTS: 'CATALOG_CATEGORY_SLUG_ALREADY_EXISTS',
  PRODUCT_NOT_FOUND: 'CATALOG_PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_ALREADY_EXISTS: 'CATALOG_PRODUCT_SLUG_ALREADY_EXISTS',
  PRODUCT_SKU_ALREADY_EXISTS: 'CATALOG_PRODUCT_SKU_ALREADY_EXISTS',
  PRODUCT_INVALID_DEMO: 'CATALOG_PRODUCT_INVALID_DEMO',
  PLAN_NOT_FOUND: 'CATALOG_PLAN_NOT_FOUND',
  PLAN_CODE_ALREADY_EXISTS: 'CATALOG_PLAN_CODE_ALREADY_EXISTS',
  VARIANT_NOT_FOUND: 'CATALOG_VARIANT_NOT_FOUND',
  VARIANT_CODE_ALREADY_EXISTS: 'CATALOG_VARIANT_CODE_ALREADY_EXISTS',
  INVALID_ATTRIBUTES: 'CATALOG_INVALID_ATTRIBUTES',
  PRICE_BOOK_NOT_FOUND: 'CATALOG_PRICE_BOOK_NOT_FOUND',
  PRICE_BOOK_INVALID: 'CATALOG_PRICE_BOOK_INVALID',
  PRICE_BOOK_DEFAULT_CONFLICT: 'CATALOG_PRICE_BOOK_DEFAULT_CONFLICT',
  PRICE_ENTRY_NOT_FOUND: 'CATALOG_PRICE_ENTRY_NOT_FOUND',
  PRICE_ENTRY_DUPLICATE: 'CATALOG_PRICE_ENTRY_DUPLICATE',
  PRICE_INVALID: 'CATALOG_PRICE_INVALID',
  PRICE_RELATION_NOT_FOUND: 'CATALOG_PRICE_RELATION_NOT_FOUND',
  PRICING_NOT_FOUND: 'CATALOG_PRICING_NOT_FOUND',
  INVALID_METADATA: 'CATALOG_INVALID_METADATA',
  INVALID_ORDER: 'CATALOG_INVALID_ORDER',
  OPERATION_FAILED: 'CATALOG_OPERATION_FAILED',
  STOCK_INVALID_ADJUSTMENT: 'CATALOG_STOCK_INVALID_ADJUSTMENT',
} as const;

export type CatalogErrorCode = (typeof CATALOG_ERROR_CODES)[keyof typeof CATALOG_ERROR_CODES];

export function catalogException(
  status: HttpStatus,
  code: CatalogErrorCode,
  message: string,
  details?: Record<string, unknown>,
): HttpException {
  return new HttpException({ statusCode: status, code, message, ...details }, status);
}
