import { HttpException, HttpStatus } from '@nestjs/common';

export const COMMERCIAL_ERROR_CODES = {
  NOT_FOUND: 'COMMERCIAL_NOT_FOUND',
  FORBIDDEN: 'COMMERCIAL_FORBIDDEN',
  INVALID_STATE: 'COMMERCIAL_INVALID_STATE',
  INVALID_MONEY: 'COMMERCIAL_INVALID_MONEY',
  UNSUPPORTED_CURRENCY: 'COMMERCIAL_UNSUPPORTED_CURRENCY',
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  SALE_OPPORTUNITY_ALREADY_CONVERTED: 'SALE_OPPORTUNITY_ALREADY_CONVERTED',
  SALE_OPPORTUNITY_PRODUCT_REQUIRED: 'SALE_OPPORTUNITY_PRODUCT_REQUIRED',
  SALE_ITEM_NOT_FOUND: 'SALE_ITEM_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_EXCEEDS_BALANCE: 'PAYMENT_EXCEEDS_SALE_BALANCE',
  PAYMENT_INVALID_REFUND: 'PAYMENT_INVALID_REFUND',
  PAYMENT_IDEMPOTENCY_CONFLICT: 'PAYMENT_IDEMPOTENCY_CONFLICT',
  PAYMENT_SALE_STATE: 'PAYMENT_SALE_STATE',
  SALE_CANCELLED_WITH_BALANCE: 'SALE_CANCELLED_WITH_BALANCE',
  PRICE_OVERRIDE_FORBIDDEN: 'PRICE_OVERRIDE_FORBIDDEN',
  SUBSCRIPTION_NOT_ELIGIBLE: 'SUBSCRIPTION_NOT_ELIGIBLE',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  RENEWAL_NOT_FOUND: 'RENEWAL_NOT_FOUND',
  RENEWAL_ALREADY_PAID: 'RENEWAL_ALREADY_PAID',
  RENEWAL_CYCLE_CONFLICT: 'RENEWAL_CYCLE_CONFLICT',
  RENEWAL_TOO_EARLY: 'RENEWAL_TOO_EARLY',
  CATALOG_NOT_FOUND: 'COMMERCIAL_CATALOG_NOT_FOUND',
  STOCK_INSUFFICIENT: 'SALE_STOCK_INSUFFICIENT',
  STOCK_INVALID_QUANTITY: 'SALE_STOCK_INVALID_QUANTITY',
} as const;

export function commercialException(
  status: HttpStatus,
  code: string,
  message: string,
  details: Readonly<Record<string, string>> = {},
): HttpException {
  return new HttpException({ statusCode: status, code, message, ...details }, status);
}
