import { HttpException, HttpStatus } from '@nestjs/common';

export const COMMERCIAL_ERROR_CODES = {
  NOT_FOUND: 'COMMERCIAL_NOT_FOUND',
  FORBIDDEN: 'COMMERCIAL_FORBIDDEN',
  INVALID_STATE: 'COMMERCIAL_INVALID_STATE',
  INVALID_MONEY: 'COMMERCIAL_INVALID_MONEY',
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  SALE_OPPORTUNITY_ALREADY_CONVERTED: 'SALE_OPPORTUNITY_ALREADY_CONVERTED',
  SALE_OPPORTUNITY_PRODUCT_REQUIRED: 'SALE_OPPORTUNITY_PRODUCT_REQUIRED',
  SALE_ITEM_NOT_FOUND: 'SALE_ITEM_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_EXCEEDS_BALANCE: 'PAYMENT_EXCEEDS_SALE_BALANCE',
  PAYMENT_INVALID_REFUND: 'PAYMENT_INVALID_REFUND',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  RENEWAL_NOT_FOUND: 'RENEWAL_NOT_FOUND',
  RENEWAL_ALREADY_PAID: 'RENEWAL_ALREADY_PAID',
  CATALOG_NOT_FOUND: 'COMMERCIAL_CATALOG_NOT_FOUND',
} as const;

export function commercialException(
  status: HttpStatus,
  code: string,
  message: string,
  details: Readonly<Record<string, string>> = {},
): HttpException {
  return new HttpException({ statusCode: status, code, message, ...details }, status);
}
