import { HttpException, HttpStatus } from '@nestjs/common';

export const OPPORTUNITY_ERROR_CODES = {
  NOT_FOUND: 'OPPORTUNITY_NOT_FOUND',
  CONTACT_NOT_FOUND: 'OPPORTUNITY_CONTACT_NOT_FOUND',
  CONTACT_ARCHIVED_FORBIDDEN: 'OPPORTUNITY_CONTACT_ARCHIVED_FORBIDDEN',
  CONTACT_ACCESS_FORBIDDEN: 'OPPORTUNITY_CONTACT_ACCESS_FORBIDDEN',
  CONTACT_UNAVAILABLE: 'OPPORTUNITY_CONTACT_UNAVAILABLE',
  STAGE_NOT_FOUND: 'OPPORTUNITY_STAGE_NOT_FOUND',
  INITIAL_STAGE_MUST_BE_OPEN: 'OPPORTUNITY_INITIAL_STAGE_MUST_BE_OPEN',
  CAMPAIGN_NOT_FOUND: 'OPPORTUNITY_CAMPAIGN_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'OPPORTUNITY_PRODUCT_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'OPPORTUNITY_CATEGORY_NOT_FOUND',
  CATEGORY_PRODUCT_MISMATCH: 'OPPORTUNITY_CATEGORY_PRODUCT_MISMATCH',
  ASSIGNEE_NOT_FOUND: 'OPPORTUNITY_ASSIGNEE_NOT_FOUND',
  UPDATE_FORBIDDEN: 'OPPORTUNITY_UPDATE_FORBIDDEN',
  ALREADY_IN_STAGE: 'OPPORTUNITY_ALREADY_IN_STAGE',
  ARCHIVED: 'OPPORTUNITY_ARCHIVED',
  CLOSED_REQUIRES_REOPEN: 'OPPORTUNITY_CLOSED_REQUIRES_REOPEN',
  LOST_REASON_REQUIRED: 'OPPORTUNITY_LOST_REASON_REQUIRED',
  HAS_ACTIVE_SALE: 'OPPORTUNITY_HAS_ACTIVE_SALE',
  INVALID_AMOUNT: 'OPPORTUNITY_INVALID_AMOUNT',
  INVALID_CURRENCY: 'OPPORTUNITY_INVALID_CURRENCY',
  OPERATION_FAILED: 'OPPORTUNITY_OPERATION_FAILED',
  STAGE_HISTORY_NOT_FOUND: 'OPPORTUNITY_STAGE_HISTORY_NOT_FOUND',
} as const;

export const PIPELINE_ERROR_CODES = {
  STAGE_NOT_FOUND: 'PIPELINE_STAGE_NOT_FOUND',
  STAGE_NAME_ALREADY_EXISTS: 'PIPELINE_STAGE_NAME_ALREADY_EXISTS',
  INVALID_COLOR: 'PIPELINE_STAGE_INVALID_COLOR',
  INVALID_ORDER: 'PIPELINE_STAGE_INVALID_ORDER',
  STAGE_IN_USE: 'PIPELINE_STAGE_IN_USE',
  LAST_OPEN_STAGE: 'PIPELINE_LAST_OPEN_STAGE',
  LAST_WON_STAGE: 'PIPELINE_LAST_WON_STAGE',
  LAST_LOST_STAGE: 'PIPELINE_LAST_LOST_STAGE',
  CATEGORY_LOCKED: 'PIPELINE_STAGE_CATEGORY_LOCKED',
  OPERATION_FAILED: 'PIPELINE_OPERATION_FAILED',
} as const;

export interface OpportunityErrorDetails {
  existingOpportunityId?: string;
  existingStageId?: string;
}

export function opportunityException(
  status: HttpStatus,
  code: string,
  message: string,
  details?: OpportunityErrorDetails,
): HttpException {
  return new HttpException({ statusCode: status, code, message, ...details }, status);
}
