import { HttpException, HttpStatus } from '@nestjs/common';

export const FOLLOW_UP_ERROR_CODES = {
  NOT_FOUND: 'FOLLOW_UP_NOT_FOUND',
  OPPORTUNITY_NOT_FOUND: 'FOLLOW_UP_OPPORTUNITY_NOT_FOUND',
  ASSIGNEE_NOT_FOUND: 'FOLLOW_UP_ASSIGNEE_NOT_FOUND',
  UPDATE_FORBIDDEN: 'FOLLOW_UP_UPDATE_FORBIDDEN',
  ALREADY_EXISTS: 'FOLLOW_UP_ALREADY_EXISTS',
  NOT_PENDING: 'FOLLOW_UP_NOT_PENDING',
  ALREADY_COMPLETED: 'FOLLOW_UP_ALREADY_COMPLETED',
  ALREADY_CANCELLED: 'FOLLOW_UP_ALREADY_CANCELLED',
  ALREADY_RESCHEDULED: 'FOLLOW_UP_ALREADY_RESCHEDULED',
  INVALID_DUE_DATE: 'FOLLOW_UP_INVALID_DUE_DATE',
  INVALID_REMINDER_DATE: 'FOLLOW_UP_INVALID_REMINDER_DATE',
  REASON_REQUIRED: 'FOLLOW_UP_REASON_REQUIRED',
  RESTORE_CONFLICT: 'FOLLOW_UP_RESTORE_CONFLICT',
  RESOURCE_UNAVAILABLE: 'FOLLOW_UP_RESOURCE_UNAVAILABLE',
  OPERATION_FAILED: 'FOLLOW_UP_OPERATION_FAILED',
  AGENDA_INVALID_DATE: 'AGENDA_INVALID_DATE',
  AGENDA_INVALID_RANGE: 'AGENDA_INVALID_RANGE',
  AGENDA_INVALID_TIMEZONE: 'AGENDA_INVALID_TIMEZONE',
  MY_DAY_INVALID_FILTER: 'MY_DAY_INVALID_FILTER',
} as const;

export interface FollowUpErrorDetails {
  existingFollowUpId?: string;
}

export function followUpException(
  status: HttpStatus,
  code: string,
  message: string,
  details?: FollowUpErrorDetails,
): HttpException {
  return new HttpException({ statusCode: status, code, message, ...details }, status);
}
