import { HttpException, HttpStatus } from '@nestjs/common';

export const WHATSAPP_ERROR_CODES = {
  CONNECTION_NOT_FOUND: 'WHATSAPP_CONNECTION_NOT_FOUND',
  CONNECTION_INVALID: 'WHATSAPP_CONNECTION_INVALID',
  CONNECTION_TEST_FAILED: 'WHATSAPP_CONNECTION_TEST_FAILED',
  CONVERSATION_NOT_FOUND: 'WHATSAPP_CONVERSATION_NOT_FOUND',
  MESSAGE_NOT_FOUND: 'WHATSAPP_MESSAGE_NOT_FOUND',
  MESSAGE_INVALID: 'WHATSAPP_MESSAGE_INVALID',
  TEMPLATE_NOT_APPROVED: 'WHATSAPP_TEMPLATE_NOT_APPROVED',
  WEBHOOK_INVALID_SIGNATURE: 'WHATSAPP_WEBHOOK_INVALID_SIGNATURE',
  WEBHOOK_INVALID_VERIFICATION: 'WHATSAPP_WEBHOOK_INVALID_VERIFICATION',
  ASSIGNEE_NOT_FOUND: 'WHATSAPP_ASSIGNEE_NOT_FOUND',
  GRAPH_API_ERROR: 'WHATSAPP_GRAPH_API_ERROR',
  READ_ONLY: 'WHATSAPP_READ_ONLY',
} as const;

export type WhatsAppErrorCode = (typeof WHATSAPP_ERROR_CODES)[keyof typeof WHATSAPP_ERROR_CODES];

export function whatsappException(
  status: HttpStatus,
  code: WhatsAppErrorCode,
  message: string,
  details?: Record<string, unknown>,
): HttpException {
  return new HttpException({ statusCode: status, code, message, ...details }, status);
}
