import { HttpException, HttpStatus } from '@nestjs/common';

export const OPERATIONS_ERROR_CODES = {
  FORBIDDEN: 'OPERATIONS_FORBIDDEN',
  NOT_FOUND: 'OPERATIONS_NOT_FOUND',
  INVALID_STATE: 'OPERATIONS_INVALID_STATE',
  INVALID_METADATA: 'OPERATIONS_INVALID_METADATA',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_INACTIVE: 'PROVIDER_INACTIVE',
  PROVIDER_SLUG_EXISTS: 'PROVIDER_SLUG_ALREADY_EXISTS',
  MAPPING_NOT_FOUND: 'PROVIDER_MAPPING_NOT_FOUND',
  MAPPING_INVALID: 'PROVIDER_MAPPING_INVALID',
  FULFILLMENT_NOT_FOUND: 'FULFILLMENT_NOT_FOUND',
  FULFILLMENT_DUPLICATE: 'FULFILLMENT_ALREADY_EXISTS',
  PROVISIONING_NOT_FOUND: 'PROVISIONING_ATTEMPT_NOT_FOUND',
  TRIAL_NOT_FOUND: 'TRIAL_NOT_FOUND',
  TRIAL_DUPLICATE: 'TRIAL_ALREADY_ACTIVE',
  TRIAL_NOT_ALLOWED: 'TRIAL_NOT_ALLOWED',
  ACTIVATION_NOT_FOUND: 'ACTIVATION_NOT_FOUND',
  ACTIVATION_DUPLICATE: 'ACTIVATION_ALREADY_EXISTS',
  CREDENTIAL_NOT_FOUND: 'CREDENTIAL_NOT_FOUND',
  CREDENTIAL_REVEAL_FORBIDDEN: 'CREDENTIAL_REVEAL_FORBIDDEN',
  CREDENTIAL_INVALID: 'CREDENTIAL_INVALID',
  CONFLICT: 'OPERATIONS_CONFLICT',
} as const;

export type OperationsErrorCode =
  (typeof OPERATIONS_ERROR_CODES)[keyof typeof OPERATIONS_ERROR_CODES];

export function operationsException(
  status: HttpStatus,
  code: OperationsErrorCode,
  message: string,
  details?: Record<string, unknown>,
): HttpException {
  return new HttpException({ statusCode: status, code, message, ...details }, status);
}
